### ISSUE TITLE
Issue with the download function

### ISSUE THREAD

**Issue by Inexpugnable** [josephsdavid/cord-19-tools#2]
With the extraction of cord-19-tools we get about 13202 documents and from the website we get 33375 json documents.

**Comment by josephsdavid** [comment]
hmm what version are you using? With the most recent version you get the proper number (had to adjust to the way they update data):

```sh
pip install --upgrade cord-19-tools 
python -c "import cotools; cotools.download('data')" && find data/ -name "*.json" | wc -l
```
Gets you all the documents (there should be close to 50,000 with the update to the dataset that came out today). I will be watching today to make sure everything is in order (they update on fridays). Be sure to upgrade tomorrow too in case there is anything strange with their update that I have to fix!

**Comment by josephsdavid** [comment]
[Updated the readme to alert of this issue](https://github.com/josephsdavid/cord-19-tools#installation)

**Comment by josephsdavid** [comment]
I'll leave this open for you to verify it works, but that should be a version issue more than anything (I fixed the hardcoding of datasets I believe two days ago)

**Comment by Inexpugnable** [comment]
I was sure I updated the package, I guess I didn't... Anyway, thank you very much for the answer.
