### ISSUE TITLE
Missing metadata.csv

### ISSUE THREAD

**Issue by motey** [josephsdavid/cord-19-tools#6]
Hey Thanks for the great toolset. i am using it for the covidgraph.org project.

with v0.3.2 and using the function `cotools.download()`
i am missing the metadata.csv file from the CORD-19 Dataset.

is it only me or do others having the same problem?
Or is this on purpose?

**Comment by josephsdavid** [comment]
I’ll look into it!

**Comment by josephsdavid** [comment]
The issue is semantic scholar keeps changing up the data structure just slightly, should have a solution for you in just a moment!

**Comment by josephsdavid** [comment]
Please update to 0.3.3! Should be fixed! Changes detailed in [this commit](https://github.com/josephsdavid/cord-19-tools/commit/688365fd3d28b8af1ab0ffba880e0ed4f0d7cc16)

**Comment by josephsdavid** [comment]
Also thanks for sharing! This knowledge graph looks really useful 😁

**Comment by josephsdavid** [comment]
Closing this unless you are still having problems!

**Comment by motey** [comment]
Sorry, missed to give feedback.
Yep works again. Thanks a lot
